"""Localized CLI copy. Command names and flags remain stable."""

CATALOG = {
    "cli.sources_help": {"en": "List the owned source catalog without network requests.", "pt-br": "Listar o catálogo próprio de fontes sem consultas de rede."},
    "cli.demo_help": {"en": "Generate synthetic JSON, Markdown and HTML without network or refinement.", "pt-br": "Gerar JSON, Markdown e HTML sintéticos sem rede nem refinamento."},
    "cli.search_help": {"en": "Compose manual search links offline; links are not findings.", "pt-br": "Compor links manuais offline; links não são achados."},
    "cli.output_dir_help": {"en": "Output directory for synthetic demo artifacts.", "pt-br": "Diretório de saída dos artefatos sintéticos."},
    "cli.search_term_help": {"en": "Literal term for manual search links.", "pt-br": "Termo literal para links de busca manual."},
    "cli.search_after_help": {"en": "Initial search date (YYYY-MM-DD).", "pt-br": "Data inicial de busca (AAAA-MM-DD)."},
    "cli.search_before_help": {"en": "Final search date (YYYY-MM-DD).", "pt-br": "Data final de busca (AAAA-MM-DD)."},
    "cli.search_file_help": {"en": "Manual search file type: pdf, docx, xlsx, pptx or txt.", "pt-br": "Tipo de arquivo na busca manual: pdf, docx, xlsx, pptx ou txt."},
    "cli.sources_notice": {"en": "Catalog inspection only; no request made. Public profiles never confirm identity.", "pt-br": "Somente inspeção do catálogo; nenhuma consulta feita. Perfis públicos nunca confirmam identidade."},
    "cli.sources_columns": {"en": "Source\tMode\tRule/version\tDocumentation or manual pivot", "pt-br": "Fonte\tModo\tRegra/versão\tDocumentação ou pivô manual"},
    "cli.source_api": {"en": "Official API (opt-in)", "pt-br": "API oficial (opcional)"},
    "cli.source_manual": {"en": "Manual only", "pt-br": "Somente manual"},
    "cli.demo_notice": {"en": "SYNTHETIC DEMO: fictitious fixtures, no DNS/HTTP/HIBP/SMTP or refinement. Not evidence of identity or mailbox existence.", "pt-br": "DEMONSTRAÇÃO SINTÉTICA: fixtures fictícias, sem DNS/HTTP/HIBP/SMTP nem refinamento. Não comprova identidade nem existência de caixa de e-mail."},
    "cli.demo_directory_invalid": {"en": "Invalid demo directory; use a separate artifact directory outside sensitive state paths.", "pt-br": "Diretório de demonstração inválido; use um diretório separado de artefatos fora dos caminhos de estado sensíveis."},
    "cli.demo_exists": {"en": "A demo destination already exists; choose another directory. Nothing was overwritten.", "pt-br": "Um destino de demonstração já existe; escolha outro diretório. Nada foi sobrescrito."},
    "cli.offline_failed": {"en": "Offline command failed: {error}", "pt-br": "Falha no comando offline: {error}"},
    "cli.search_notice": {"en": "MANUAL LINKS, NOT FINDINGS: no search was performed; dates and file types are search-engine hints, not guarantees.", "pt-br": "LINKS MANUAIS, NÃO ACHADOS: nenhuma busca foi executada; datas e tipos de arquivo são sugestões ao buscador, não garantias."},
    "cli.search_date_invalid": {"en": "Invalid date; use a valid YYYY-MM-DD date.", "pt-br": "Data inválida; use uma data válida AAAA-MM-DD."},
    "cli.search_date_order": {"en": "Initial date must not be after final date.", "pt-br": "A data inicial não pode ser posterior à final."},
    "cli.search_file_invalid": {"en": "Unsupported file type; allowed: {choices}.", "pt-br": "Tipo de arquivo não permitido; opções: {choices}."},
    "cli.search_text_invalid": {"en": "Invalid or excessive manual search terms.", "pt-br": "Termos de busca manual inválidos ou excessivos."},
    "cli.search_domain_invalid": {"en": "Invalid search domain; supply only a DNS domain, not a URL or operator.", "pt-br": "Domínio de busca inválido; forneça somente domínio DNS, não URL nem operador."},
    "cli.html_help": {"en": "Write an offline HTML report.", "pt-br": "Gravar relatório HTML offline."},
    "cli.html_saved": {"en": "HTML report saved to: {path}", "pt-br": "Relatório HTML salvo em: {path}"},
    "cli.description": {"en": "Educational CLI for email recon and validation.", "pt-br": "CLI educacional para reconhecimento e validação de e-mails."},
    "cli.group": {"en": "MailRecon command group.", "pt-br": "Comandos do MailRecon."},
    "cli.usage": {"en": "Usage:", "pt-br": "Uso:"},
    "cli.options": {"en": "Options", "pt-br": "Opções"},
    "cli.arguments": {"en": "Arguments", "pt-br": "Argumentos"},
    "cli.commands": {"en": "Commands", "pt-br": "Comandos"},
    "cli.help": {"en": "Show this message and exit.", "pt-br": "Mostrar esta ajuda e sair."},
    "cli.default": {"en": "default", "pt-br": "padrão"},
    "cli.required": {"en": "required", "pt-br": "obrigatório"},
    "cli.language_help": {"en": "Interface language: pt-br or en.", "pt-br": "Idioma da interface: pt-br ou en."},
    "cli.analyze_help": {"en": "Analyze an email address using public and permitted data sources.", "pt-br": "Analisar um e-mail usando fontes públicas e permitidas."},
    "cli.investigate_help": {"en": "Run a reusable OSINT investigation focused on email pivots and evidence.", "pt-br": "Investigar indicadores OSINT com candidatos e evidências rastreáveis."},
    "cli.interactive_help": {"en": "Guide an investigation step by step with interactive prompts.", "pt-br": "Conduzir uma investigação por perguntas interativas."},
    "cli.lab_admin_help": {"en": "Run a lab-only simulation of public profile resolution states.", "pt-br": "Simular estados de perfis públicos exclusivamente em laboratório."},
    "cli.smtp_help": {"en": "Run lab-only SMTP validation with strict safety gates.", "pt-br": "Validar SMTP de laboratório com controles de segurança estritos."},
    "cli.rerun_help": {"en": "Repeat the latest saved investigation using the refinement file state.", "pt-br": "Repetir a última investigação com o estado de refinamento salvo."},
    "cli.invalid_investigation": {"en": "Invalid investigation input: {error}", "pt-br": "Entrada inválida para investigação: {error}"},
    "cli.investigation_failed": {"en": "Investigation failed: {error}", "pt-br": "Falha na investigação: {error}"},
    "cli.invalid_input": {"en": "Invalid input: {error}", "pt-br": "Entrada inválida: {error}"},
    "cli.analysis_failed": {"en": "Analysis failed: {error}", "pt-br": "Falha na análise: {error}"},
    "cli.invalid_smtp": {"en": "Invalid lab SMTP input: {error}", "pt-br": "Entrada inválida para SMTP de laboratório: {error}"},
    "cli.smtp_failed": {"en": "Lab SMTP validation failed: {error}", "pt-br": "Falha na validação SMTP de laboratório: {error}"},
    "cli.rerun_failed": {"en": "Unable to rerun the last investigation: {error}", "pt-br": "Não foi possível repetir a última investigação: {error}"},
    "cli.refinement_ready": {"en": "Refinement file ready at: {path}", "pt-br": "Arquivo de refinamento disponível em: {path}"},
    "cli.exclusions": {"en": "Applied refinement exclusions: {count} link(s).", "pt-br": "Exclusões de refinamento aplicadas: {count} link(s)."},
    "cli.json_saved": {"en": "JSON report saved to: {path}", "pt-br": "Relatório JSON salvo em: {path}"},
    "cli.markdown_saved": {"en": "Markdown report saved to: {path}", "pt-br": "Relatório Markdown salvo em: {path}"},
    "cli.interactive_title": {"en": "MailRecon interactive investigation", "pt-br": "Investigação interativa MailRecon"},
    "cli.skip": {"en": "Press Enter to skip any optional field.", "pt-br": "Pressione Enter para pular qualquer campo opcional."},
    "cli.name": {"en": "Name", "pt-br": "Nome"},
    "cli.email": {"en": "Email", "pt-br": "E-mail"},
    "cli.username": {"en": "Username", "pt-br": "Nome de usuário"},
    "cli.domain": {"en": "Domain", "pt-br": "Domínio"},
    "cli.organization": {"en": "Organization", "pt-br": "Organização"},
    "cli.context": {"en": "Context", "pt-br": "Contexto"},
    "cli.candidate_email": {"en": "Candidate email", "pt-br": "E-mail candidato"},
    "cli.list_prompt": {"en": "{label}(s)", "pt-br": "{label} (separe por vírgulas)"},
    "cli.save_json": {"en": "Save the investigation as JSON?", "pt-br": "Salvar a investigação em JSON?"},
    "cli.save_markdown": {"en": "Save the investigation as Markdown?", "pt-br": "Salvar a investigação em Markdown?"},
    "cli.json_path": {"en": "JSON output path", "pt-br": "Caminho do arquivo JSON"},
    "cli.markdown_path": {"en": "Markdown output path", "pt-br": "Caminho do arquivo Markdown"},
    "cli.markdown_prompt": {"en": "Markdown language (en or pt-br)", "pt-br": "Idioma do Markdown (pt-br ou en)"},
    "cli.check_profiles": {"en": "Resolve generated public profile URLs with safe public-only checks?", "pt-br": "Verificar as URLs de perfis geradas somente por páginas públicas?"},
    "cli.reload": {"en": "Reloading the latest saved investigation parameters...", "pt-br": "Carregando os parâmetros da última investigação salva..."},
    "cli.confirm_hint_yes": {"en": "Y/n", "pt-br": "S/n"},
    "cli.confirm_hint_no": {"en": "y/N", "pt-br": "s/N"},
    "cli.confirm_invalid": {"en": "Answer yes or no.", "pt-br": "Responda sim ou não."},
    "cli.error": {"en": "Error: {error}", "pt-br": "Erro: {error}"},
    "cli.bad_value": {"en": "Invalid value for {option}: {error}", "pt-br": "Valor inválido para {option}: {error}"},
    "cli.missing": {"en": "Missing {kind} {option}.", "pt-br": "Falta {kind} {option}."},
    "cli.argument_kind": {"en": "argument", "pt-br": "o argumento"},
    "cli.option_kind": {"en": "option", "pt-br": "a opção"},
    "cli.no_option": {"en": "No such option: {option}", "pt-br": "Opção inexistente: {option}"},
    "cli.no_command": {"en": "No such command '{command}'.", "pt-br": "Comando inexistente '{command}'."},
    "cli.choice": {"en": "'{value}' is not one of {choices}.", "pt-br": "'{value}' não é uma das opções {choices}."},
    "cli.invalid_language": {"en": "Choose pt-br or en.", "pt-br": "Escolha pt-br ou en."},
    "cli.abort": {"en": "Aborted.", "pt-br": "Operação cancelada."},
    "cli.install_completion": {"en": "Install completion for the current shell.", "pt-br": "Instalar autocompletar no shell atual."},
    "cli.show_completion": {"en": "Show completion for the current shell, to copy it or customize the installation.", "pt-br": "Mostrar o autocompletar do shell atual para instalação personalizada."},
    "cli.lab_context": {"en": "lab-only public profile simulation", "pt-br": "simulação sintética de perfil público em laboratório"},
    "cli.export_failed": {"en": "Unable to save report to {path}: {error}", "pt-br": "Não foi possível salvar o relatório em {path}: {error}"},
    "cli.integer_invalid": {"en": "'{value}' is not a valid integer.", "pt-br": "'{value}' não é um número inteiro válido."},
    "cli.integer_range_invalid": {"en": "'{value}' is not a valid integer range.", "pt-br": "'{value}' não é um número inteiro válido para o intervalo."},
    "cli.range_invalid": {"en": "{value} is not in the range {range}.", "pt-br": "{value} está fora do intervalo {range}."},
    "cli.option_argument": {"en": "Option '{option}' requires an argument.", "pt-br": "A opção '{option}' exige um argumento."},
    "cli.option_no_value": {"en": "Option '{option}' does not take a value.", "pt-br": "A opção '{option}' não aceita um valor."},
    "cli.extra_argument": {"en": "Got unexpected extra argument ({value})", "pt-br": "Argumento extra inesperado ({value})"},
    "cli.extra_arguments": {"en": "Got unexpected extra arguments ({value})", "pt-br": "Argumentos extras inesperados ({value})"},
}

HELP_COPY = {
    "email_help": ("Email address to analyze.", "Endereço de e-mail para analisar."),
    "json_help": ("Write the full result as JSON.", "Exportar o resultado completo em JSON."),
    "markdown_help": ("Write the full result as Markdown.", "Exportar o resultado completo em Markdown."),
    "reveal_help": ("Show full email addresses in terminal summaries and Markdown reports.", "Exibir e-mails completos no terminal e nos relatórios Markdown."),
    "hibp_help": ("Enable or disable Have I Been Pwned lookups.", "Ativar ou desativar consultas ao Have I Been Pwned."),
    "name_seed_help": ("Name seed for the investigation. Repeat the option when needed.", "Nome inicial para investigação. A opção pode ser repetida."),
    "email_seed_help": ("Email seed for the investigation. Repeat the option when needed.", "E-mail inicial para investigação. A opção pode ser repetida."),
    "username_seed_help": ("Username seed for the investigation. Repeat the option when needed.", "Nome de usuário inicial. A opção pode ser repetida."),
    "domain_seed_help": ("Domain seed for the investigation. Repeat the option when needed.", "Domínio inicial. A opção pode ser repetida."),
    "organization_seed_help": ("Organization seed for the investigation. Repeat the option when needed.", "Organização inicial. A opção pode ser repetida."),
    "context_help": ("Context note that explains why the investigation is being opened.", "Contexto que justifica a investigação autorizada."),
    "candidate_help": ("Explicit candidate email to retain during the investigation.", "E-mail candidato informado explicitamente."),
    "profiles_help": ("Resolve only public profile URLs already generated by the investigation.", "Verificar somente URLs de perfis públicos já geradas."),
    "investigation_json_help": ("Write the structured investigation result as JSON.", "Exportar a investigação estruturada em JSON."),
    "investigation_md_help": ("Write the investigation report as Markdown.", "Exportar o relatório de investigação em Markdown."),
    "markdown_language_help": ("Markdown report language: en or pt-br.", "Idioma do relatório Markdown: pt-br ou en; padrão igual ao terminal."),
    "handle_help": ("Username or handle seed.", "Nome de usuário inicial."),
    "optional_domain_help": ("Optional domain seed.", "Domínio inicial opcional."),
    "optional_email_help": ("Optional email seed.", "E-mail inicial opcional."),
    "scenario_help": ("Lab-only profile scenario: found, not-found, ambiguous, blocked, or rate-limited.", "Cenário sintético: found, not-found, ambiguous, blocked ou rate-limited."),
    "lab_email_help": ("Lab email address to validate.", "E-mail de laboratório para validar."),
    "lab_domain_help": ("Explicit lab domain that must match the email domain.", "Domínio explícito do laboratório, igual ao domínio do e-mail."),
    "smtp_host_help": ("Explicit lab SMTP host. MX discovery is intentionally not supported.", "Host SMTP explícito do laboratório. Sem descoberta por MX."),
    "smtp_port_help": ("Explicit lab SMTP port.", "Porta SMTP explícita do laboratório."),
    "transport_help": ("Lab transport: mock, localhost, or private-lab.", "Transporte: mock, localhost ou private-lab."),
    "check_help": ("Lab SMTP check to run: vrfy, rcpt, or expn. Repeat up to --max-probes.", "Checagem SMTP: vrfy, rcpt ou expn. Repetir até --max-probes."),
    "lab_confirm_help": ("Required for networked lab SMTP checks.", "Obrigatório para checagens SMTP de laboratório com rede."),
    "no_network_help": ("Force mock-only execution and block networked transports.", "Forçar simulação e bloquear transportes com rede."),
    "max_probes_help": ("Hard limit for requested lab SMTP probes.", "Limite rígido de checagens SMTP solicitadas."),
    "smtp_json_help": ("Write the lab SMTP result as JSON.", "Exportar o resultado SMTP de laboratório em JSON."),
    "smtp_md_help": ("Write the lab SMTP result as Markdown.", "Exportar o resultado SMTP de laboratório em Markdown."),
}
CATALOG.update({f"cli.{key}": {"en": en, "pt-br": pt} for key, (en, pt) in HELP_COPY.items()})
