"""UTF-8 catalogs for service-owned prose, including legacy authored templates.

Keys are stable dotted identifiers. Named parameters preserve user values,
technical identifiers, and upstream details verbatim in both languages.
"""

CATALOG = {
    "i18n.error.language": {"en": "Unsupported language: {requested_language}. Choose pt-br or en.", "pt-br": "Idioma não suportado: {requested_language}. Escolha pt-br ou en."},
    "validation.email.invalid": {"en": "{detail}", "pt-br": "Endereço de e-mail inválido: {detail}"},
    "validation.email.missing_at": {"en": "An email address must have an @-sign.", "pt-br": "Um endereço de e-mail deve conter o sinal @."},
    "validation.email.missing_local": {"en": "There must be something before the @-sign.", "pt-br": "Deve haver um nome antes do sinal @."},
    "validation.email.missing_domain": {"en": "There must be something after the @-sign.", "pt-br": "Deve haver um domínio após o sinal @."},
    "validation.email.domain_period": {"en": "The part after the @-sign is not valid. It should have a period.", "pt-br": "A parte após o sinal @ é inválida. Ela deve conter um ponto."},
    "validation.email.characters_before": {"en": "The email address contains invalid characters before the @-sign: {characters}.", "pt-br": "O endereço de e-mail contém caracteres inválidos antes do sinal @: {characters}."},
    "validation.email.characters_after": {"en": "The part after the @-sign contains invalid characters: {characters}.", "pt-br": "A parte após o sinal @ contém caracteres inválidos: {characters}."},
    "validation.email.special_domain": {"en": "The part after the @-sign is a special-use or reserved name that cannot be used with email.", "pt-br": "A parte após o sinal @ é um nome reservado ou de uso especial que não pode ser usado em e-mails."},
    "recon.progress.validate": {"en": "Validating email format...", "pt-br": "Validando o formato do e-mail..."},
    "recon.progress.dns": {"en": "Checking DNS and MX records for {domain}...", "pt-br": "Consultando registros DNS e MX de {domain}..."},
    "recon.progress.hibp": {"en": "Querying HIBP for {email}...", "pt-br": "Consultando o HIBP para {email}..."},
    "recon.reason.valid_syntax": {"en": "Email syntax is valid.", "pt-br": "A sintaxe do e-mail é válida."},
    "recon.reason.domain_status": {"en": "Domain status is {status}.", "pt-br": "O status do domínio é {status}."},
    "recon.reason.mail_status": {"en": "Email acceptance status is {status}.", "pt-br": "O status de recebimento de e-mails é {status}."},
    "recon.reason.provider": {"en": "Provider family is {provider}.", "pt-br": "A família do provedor é {provider}."},
    "recon.reason.spf": {"en": "Domain publishes SPF.", "pt-br": "O domínio publica SPF."},
    "recon.reason.dmarc": {"en": "Domain publishes DMARC.", "pt-br": "O domínio publica DMARC."},
    "recon.reason.disposable": {"en": "Domain is on the local disposable-domain list.", "pt-br": "O domínio está na lista local de domínios de e-mail descartável."},
    "recon.reason.role": {"en": "Local-part looks like a role or shared mailbox.", "pt-br": "A parte local parece corresponder a uma função ou caixa de correio compartilhada."},
    "recon.limitation.mailbox": {"en": "Technical assessment does not confirm individual mailbox existence.", "pt-br": "A avaliação técnica não confirma a existência de uma caixa de correio individual."},
    "recon.limitation.catch_all": {"en": "Catch-all status is not tested because MailRecon avoids SMTP probing.", "pt-br": "O recebimento genérico (catch-all) não é testado porque o MailRecon evita sondagens SMTP."},
    "dns.error.nxdomain": {"en": "Domain does not exist in DNS.", "pt-br": "O domínio não existe no DNS."},
    "dns.error.no_records": {"en": "No {record_type} records found.", "pt-br": "Nenhum registro {record_type} encontrado."},
    "dns.error.nameservers": {"en": "No nameservers responded to the DNS query.", "pt-br": "Nenhum servidor de nomes respondeu à consulta DNS."},
    "dns.error.timeout": {"en": "DNS lookup for {record_type} timed out.", "pt-br": "A consulta DNS de {record_type} atingiu o tempo limite."},
    "dns.error.lifetime_timeout": {"en": "DNS lookup for {record_type} exceeded the configured timeout.", "pt-br": "A consulta DNS de {record_type} excedeu o tempo limite configurado."},
    "dns.error.query": {"en": "DNS error while querying {record_type}: {error}", "pt-br": "Erro DNS ao consultar {record_type}: {error}"},
    "dns.error.no_dmarc": {"en": "No DMARC records found.", "pt-br": "Nenhum registro DMARC encontrado."},
    "dns.reason.null_mx": {"en": "Domain publishes Null MX and declares it does not accept email.", "pt-br": "O domínio publica Null MX e declara que não aceita e-mails."},
    "hibp.error.timeout": {"en": "HIBP request timed out.", "pt-br": "A consulta ao HIBP atingiu o tempo limite."},
    "hibp.error.request": {"en": "HIBP request failed: {error}", "pt-br": "A consulta ao HIBP falhou: {error}"},
    "hibp.error.unauthorized": {"en": "HIBP rejected the API key.", "pt-br": "O HIBP rejeitou a chave de API."},
    "hibp.error.forbidden": {"en": "HIBP denied access to this request.", "pt-br": "O HIBP negou acesso a esta consulta."},
    "hibp.error.rate_limited": {"en": "HIBP rate limit reached. Try again later.", "pt-br": "O limite de consultas do HIBP foi atingido. Tente novamente mais tarde."},
    "hibp.error.http": {"en": "HIBP returned HTTP {status_code}.", "pt-br": "O HIBP retornou HTTP {status_code}."},
    "hibp.error.json": {"en": "HIBP returned a response that was not valid JSON.", "pt-br": "O HIBP retornou uma resposta que não é um JSON válido."},
    "hibp.error.shape": {"en": "HIBP returned an unexpected response shape.", "pt-br": "O HIBP retornou uma estrutura de resposta inesperada."},
    "refinement.instructions": {"en": "Add public-profile links that were manually disproved to 'excluded_profile_urls' and rerun the same investigation to hide them.", "pt-br": "Adicione links de perfis públicos descartados manualmente a 'excluded_profile_urls' e execute novamente a mesma investigação para ocultá-los."},
    "refinement.error.missing": {"en": "No saved investigation refinement file was found.", "pt-br": "Nenhum arquivo de refinamento de investigação salvo foi encontrado."},
    "refinement.error.unreadable": {"en": "The saved investigation refinement file is unreadable.", "pt-br": "Não foi possível ler o arquivo de refinamento de investigação salvo."},
    "refinement.error.parameters": {"en": "The saved refinement file does not contain investigation parameters.", "pt-br": "O arquivo de refinamento salvo não contém parâmetros de investigação."},
    "refinement.limitation.excluded": {"en": "{count} public-profile link(s) were manually excluded through the refinement file.", "pt-br": "{count} link(s) de perfis públicos foram excluídos manualmente pelo arquivo de refinamento."},
    "safety.limitation.owned_lab": {"en": "Lab SMTP validation is for owned, closed test infrastructure only.", "pt-br": "A validação SMTP de laboratório é exclusiva para infraestrutura de testes própria e fechada."},
    "safety.limitation.mailbox": {"en": "Results describe the tested lab server interaction and do not prove real mailbox existence.", "pt-br": "Os resultados descrevem a interação com o servidor de laboratório testado e não comprovam a existência de uma caixa de correio real."},
    "safety.limitation.no_mx": {"en": "MailRecon does not perform MX discovery for lab SMTP validation; the lab host must be supplied explicitly.", "pt-br": "O MailRecon não faz descoberta de MX na validação SMTP de laboratório; o host de laboratório deve ser informado explicitamente."},
    "safety.reason.transport": {"en": "Unsupported lab SMTP transport: {transport}.", "pt-br": "Transporte SMTP de laboratório não suportado: {transport}."},
    "safety.reason.checks": {"en": "Unsupported lab SMTP check(s): {checks}.", "pt-br": "Verificação(ões) SMTP de laboratório não suportada(s): {checks}."},
    "safety.reason.no_checks": {"en": "At least one lab SMTP check must be requested.", "pt-br": "É necessário solicitar pelo menos uma verificação SMTP de laboratório."},
    "safety.reason.probe_range": {"en": "max_probes must be between 1 and 3.", "pt-br": "max_probes deve estar entre 1 e 3."},
    "safety.reason.probe_limit": {"en": "Requested checks exceed max_probes.", "pt-br": "As verificações solicitadas excedem max_probes."},
    "safety.reason.domain_required": {"en": "A lab domain is required.", "pt-br": "É necessário informar um domínio de laboratório."},
    "safety.reason.domain_mismatch": {"en": "Email domain must match the explicit lab domain.", "pt-br": "O domínio do e-mail deve corresponder ao domínio de laboratório informado explicitamente."},
    "safety.reason.no_network": {"en": "--no-network only permits mock transport.", "pt-br": "--no-network permite apenas o transporte mock."},
    "safety.reason.env_gate": {"en": "MAILRECON_ENABLE_LAB_SMTP=1 is required for networked lab SMTP.", "pt-br": "MAILRECON_ENABLE_LAB_SMTP=1 é obrigatório para SMTP de laboratório com rede."},
    "safety.reason.confirmation": {"en": "--confirm-lab-only is required for networked lab SMTP.", "pt-br": "--confirm-lab-only é obrigatório para SMTP de laboratório com rede."},
    "safety.reason.host_required": {"en": "A lab host is required for networked lab SMTP.", "pt-br": "É necessário informar um host para SMTP de laboratório com rede."},
    "safety.reason.allow_hosts": {"en": "private-lab transport requires explicit allow hosts.", "pt-br": "O transporte private-lab exige hosts permitidos explicitamente."},
    "safety.reason.port_range": {"en": "Port must be between 1 and 65535.", "pt-br": "A porta deve estar entre 1 e 65535."},
    "safety.reason.public_ports": {"en": "Common public SMTP ports are blocked outside loopback lab hosts.", "pt-br": "As portas SMTP públicas comuns são bloqueadas fora de hosts de laboratório em loopback."},
    "safety.reason.expn": {"en": "EXPN is allowed only for mock or localhost lab transport.", "pt-br": "EXPN é permitido apenas nos transportes de laboratório mock ou localhost."},
    "safety.reason.passed": {"en": "All lab-only SMTP safety controls passed.", "pt-br": "Todos os controles de segurança SMTP exclusivos de laboratório foram aprovados."},
    "safety.reason.host_type": {"en": "Lab SMTP host must be localhost, a literal lab IP, or an allowed host.", "pt-br": "O host SMTP de laboratório deve ser localhost, um IP literal de laboratório ou um host permitido."},
    "safety.reason.loopback": {"en": "localhost transport only permits loopback addresses.", "pt-br": "O transporte localhost permite apenas endereços de loopback."},
    "safety.reason.private_ip": {"en": "private-lab transport only permits loopback, private, or link-local addresses.", "pt-br": "O transporte private-lab permite apenas endereços de loopback, privados ou link-local."},
    "safety.reason.host_transport": {"en": "Unsupported network transport for host classification.", "pt-br": "Transporte de rede não suportado para classificação do host."},
    "smtp.message.blocked": {"en": "Blocked before any SMTP interaction.", "pt-br": "Bloqueado antes de qualquer interação SMTP."},
    "smtp.message.mock": {"en": "Mock lab transport result; no network used.", "pt-br": "Resultado do transporte simulado de laboratório; nenhuma rede utilizada."},
    "smtp.error.interaction": {"en": "Lab SMTP interaction failed: {error}", "pt-br": "A interação SMTP de laboratório falhou: {error}"},
    "smtp.error.check": {"en": "Unsupported lab SMTP check.", "pt-br": "Verificação SMTP de laboratório não suportada."},
    "smtp.error.email_at": {"en": "Lab SMTP email must contain exactly one @ sign.", "pt-br": "O e-mail SMTP de laboratório deve conter exatamente um sinal @."},
    "smtp.error.email_parts": {"en": "Lab SMTP email must include local-part and domain.", "pt-br": "O e-mail SMTP de laboratório deve incluir a parte local e o domínio."},
    "smtp.error.local_characters": {"en": "Lab SMTP email local-part contains unsupported characters.", "pt-br": "A parte local do e-mail SMTP de laboratório contém caracteres não suportados."},
    "smtp.error.empty_label": {"en": "Lab SMTP email domain contains an empty label.", "pt-br": "O domínio do e-mail SMTP de laboratório contém um segmento vazio."},
    "smtp.error.domain_characters": {"en": "Lab SMTP email domain contains unsupported characters.", "pt-br": "O domínio do e-mail SMTP de laboratório contém caracteres não suportados."},
    "smtp.error.hyphen": {"en": "Lab SMTP email domain labels cannot start or end with hyphen.", "pt-br": "Os segmentos do domínio do e-mail SMTP de laboratório não podem começar ou terminar com hífen."},
    "investigation.progress.seeds": {"en": "Preparing investigation seeds...", "pt-br": "Preparando os dados iniciais da investigação..."},
    "investigation.progress.candidates": {"en": "Building candidate emails...", "pt-br": "Criando e-mails candidatos..."},
    "investigation.progress.pivots": {"en": "Generating public-profile pivots...", "pt-br": "Gerando caminhos de pesquisa de perfis públicos..."},
    "investigation.progress.analyze": {"en": "Analyzing candidate email: {email}", "pt-br": "Analisando o e-mail candidato: {email}"},
    "investigation.progress.domains": {"en": "Collecting domain evidence...", "pt-br": "Coletando evidências de domínio..."},
    "investigation.progress.profiles": {"en": "Checking public profile URLs...", "pt-br": "Verificando URLs de perfis públicos..."},
    "investigation.progress.finalize": {"en": "Finalizing investigation summary...", "pt-br": "Finalizando o resumo da investigação..."},
    "investigation.finding.breaches": {"en": "{email} appeared in {count} public breach record(s).", "pt-br": "{email} apareceu em {count} registro(s) público(s) de vazamento."},
    "investigation.risk.exposure": {"en": "Public breach exposure may increase phishing or account recovery risk for {email}.", "pt-br": "A exposição em vazamentos públicos pode aumentar o risco de phishing ou de recuperação indevida de conta para {email}."},
    "investigation.finding.mx": {"en": "Domain {domain} resolves publicly and exposes MX infrastructure.", "pt-br": "O domínio {domain} resolve publicamente e expõe infraestrutura MX."},
    "investigation.risk.domain": {"en": "Domain {domain} did not resolve during collection and may be stale, parked, or mistyped.", "pt-br": "O domínio {domain} não resolveu durante a coleta e pode estar desatualizado, estacionado ou digitado incorretamente."},
    "investigation.finding.candidates": {"en": "The investigation organized {count} candidate email(s) for safe review.", "pt-br": "A investigação organizou {count} e-mail(s) candidato(s) para revisão segura."},
    "investigation.limitation.no_candidates": {"en": "No candidate emails were produced from the provided seeds, so email-centric pivots are limited.", "pt-br": "Nenhum e-mail candidato foi produzido a partir dos dados iniciais fornecidos, limitando os caminhos de pesquisa centrados em e-mail."},
    "investigation.finding.pivots": {"en": "The investigation generated {count} safe public-profile pivot suggestion(s) for manual review.", "pt-br": "A investigação gerou {count} sugestão(ões) segura(s) de pesquisa de perfis públicos para revisão manual."},
    "investigation.error.seeds": {"en": "Provide at least one seed such as --email, --name, --username, --domain, --organization, or --context.", "pt-br": "Forneça pelo menos um dado inicial, como --email, --name, --username, --domain, --organization ou --context."},
    "investigation.seed.title": {"en": "Seed {label}", "pt-br": "Dado inicial: {label}"},
    "investigation.seed.reference": {"en": "CLI input", "pt-br": "Entrada da CLI"},
    "investigation.seed.summary": {"en": "The investigation started with {label}: {value}", "pt-br": "A investigação começou com {label}: {value}"},
    "investigation.reason.invalid_format": {"en": "Email format validation failed.", "pt-br": "A validação do formato do e-mail falhou."},
    "investigation.limitation.invalid_syntax": {"en": "Invalid email syntax prevents further technical assessment.", "pt-br": "A sintaxe inválida do e-mail impede avaliações técnicas adicionais."},
    "investigation.reason.direct_seed": {"en": "Retained because the email was provided directly as an investigation seed.", "pt-br": "Mantido porque o e-mail foi fornecido diretamente como dado inicial da investigação."},
    "investigation.reason.provided_candidate": {"en": "Retained because it was explicitly provided as a candidate email.", "pt-br": "Mantido porque foi fornecido explicitamente como e-mail candidato."},
    "investigation.reason.username_inference": {"en": "Generated from username plus domain; this is an inferred lead.", "pt-br": "Gerado a partir de nome de usuário e domínio; trata-se de uma pista inferida."},
    "investigation.reason.name_inference": {"en": "Generated from name pattern plus domain; this is a weak inferred lead.", "pt-br": "Gerado a partir de padrão de nome e domínio; trata-se de uma pista inferida fraca."},
    "investigation.reason.unverified": {"en": "Retained as a syntactically valid but unverified email candidate.", "pt-br": "Mantido como e-mail candidato com sintaxe válida, mas não verificado."},
    "investigation.reason.syntax": {"en": "Email syntax is valid; mailbox existence is not confirmed.", "pt-br": "A sintaxe do e-mail é válida; a existência da caixa de correio não está confirmada."},
    "investigation.limitation.format": {"en": "A valid email format does not prove the mailbox exists.", "pt-br": "Um formato de e-mail válido não comprova que a caixa de correio existe."},
    "investigation.limitation.no_probing": {"en": "No SMTP probing, login flow, password recovery, VRFY, or RCPT TO checks are performed.", "pt-br": "Não são realizadas sondagens SMTP, fluxos de login, recuperação de senha ou verificações VRFY e RCPT TO."},
    "investigation.reason.role": {"en": "Role accounts are weaker evidence for personal identity correlation.", "pt-br": "Contas de função são evidências mais fracas para correlação de identidade pessoal."},
    "investigation.limitation.role": {"en": "Role/shared mailboxes may belong to teams rather than one person.", "pt-br": "Caixas de correio de função ou compartilhadas podem pertencer a equipes, e não a uma pessoa."},
    "investigation.reason.disposable": {"en": "Disposable domains are weak evidence for durable identity correlation.", "pt-br": "Domínios descartáveis são evidências fracas para correlação duradoura de identidade."},
    "investigation.limitation.disposable": {"en": "Disposable domains can create false positives in identity investigations.", "pt-br": "Domínios descartáveis podem gerar falsos positivos em investigações de identidade."},
    "investigation.reason.nxdomain": {"en": "Domain returned NXDOMAIN during public DNS collection.", "pt-br": "O domínio retornou NXDOMAIN durante a coleta de DNS público."},
    "investigation.limitation.unresolved": {"en": "The domain did not resolve publicly at collection time.", "pt-br": "O domínio não resolveu publicamente no momento da coleta."},
    "investigation.limitation.null_mx": {"en": "Null MX is a domain-level signal, not a mailbox-level response.", "pt-br": "Null MX é um sinal do domínio, não uma resposta de uma caixa de correio."},
    "investigation.reason.mx": {"en": "Domain publishes MX records, so it appears mail-capable.", "pt-br": "O domínio publica registros MX, portanto parece capaz de receber e-mails."},
    "investigation.limitation.mx": {"en": "MX records validate domain mail capability, not this mailbox.", "pt-br": "Registros MX validam a capacidade de e-mail do domínio, não esta caixa de correio."},
    "investigation.reason.no_mx": {"en": "Domain has address records but no MX records.", "pt-br": "O domínio possui registros de endereço, mas não registros MX."},
    "investigation.limitation.implicit_mail": {"en": "Implicit mail delivery without MX is possible but weak evidence.", "pt-br": "A entrega implícita de e-mail sem MX é possível, mas constitui evidência fraca."},
    "investigation.reason.mail_status": {"en": "Domain mail acceptance status is {status}.", "pt-br": "O status de recebimento de e-mails do domínio é {status}."},
    "investigation.limitation.mail_signal": {"en": "DNS collection did not provide a strong mail-capability signal.", "pt-br": "A coleta de DNS não forneceu um sinal forte de capacidade de recebimento de e-mails."},
    "investigation.reason.spf": {"en": "Domain publishes SPF; this is hygiene evidence, not mailbox proof.", "pt-br": "O domínio publica SPF; isso é evidência de boas práticas, não comprovação de caixa de correio."},
    "investigation.reason.dmarc": {"en": "Domain publishes DMARC; this is governance evidence, not mailbox proof.", "pt-br": "O domínio publica DMARC; isso é evidência de governança, não comprovação de caixa de correio."},
    "investigation.evidence.candidate_title": {"en": "Candidate email validation", "pt-br": "Validação de e-mail candidato"},
    "investigation.evidence.candidate_summary": {"en": "{email} was retained as a {source} candidate.", "pt-br": "{email} foi mantido como candidato de origem {source}."},
    "investigation.evidence.hibp_title": {"en": "HIBP exposure check", "pt-br": "Verificação de exposição no HIBP"},
    "investigation.evidence.hibp_summary": {"en": "{email} returned HIBP status {status}.", "pt-br": "{email} retornou o status HIBP {status}."},
    "investigation.limitation.hibp": {"en": "HIBP exposure status is a third-party public breach signal, not proof of mailbox control.", "pt-br": "O status de exposição no HIBP é um sinal de vazamento público de terceiros, não uma comprovação de controle da caixa de correio."},
    "investigation.limitation.no_breaches": {"en": "Absence of known breaches does not prove the address is inactive or safe.", "pt-br": "A ausência de vazamentos conhecidos não comprova que o endereço esteja inativo ou seguro."},
    "investigation.evidence.domain_title": {"en": "Domain infrastructure check", "pt-br": "Verificação da infraestrutura do domínio"},
    "investigation.evidence.domain_resolves": {"en": "Domain {domain} resolves publicly with {a_count} A record(s) and {mx_count} MX host(s).", "pt-br": "O domínio {domain} resolve publicamente com {a_count} registro(s) A e {mx_count} host(s) MX."},
    "investigation.evidence.domain_unresolved": {"en": "Domain {domain} did not resolve during the DNS collection step.", "pt-br": "O domínio {domain} não resolveu durante a etapa de coleta DNS."},
    "investigation.reason.domain_status": {"en": "Domain status: {status}.", "pt-br": "Status do domínio: {status}."},
    "investigation.reason.email_status": {"en": "Email acceptance status: {status}.", "pt-br": "Status de recebimento de e-mails: {status}."},
    "investigation.reason.provider": {"en": "Provider family: {provider}.", "pt-br": "Família do provedor: {provider}."},
    "investigation.limitation.dns": {"en": "DNS describes domain infrastructure and does not confirm individual mailbox existence.", "pt-br": "O DNS descreve a infraestrutura do domínio e não confirma a existência de uma caixa de correio individual."},
    "investigation.pivot.naming": {"en": "Compare candidate email naming patterns to decide which local-part formats deserve manual validation in public records.", "pt-br": "Compare os padrões de nomes dos e-mails candidatos para decidir quais formatos de parte local merecem validação manual em registros públicos."},
    "investigation.pivot.domains": {"en": "Review the discovered domains and MX providers to map shared infrastructure and likely communication providers.", "pt-br": "Revise os domínios e provedores MX descobertos para mapear infraestrutura compartilhada e prováveis provedores de comunicação."},
    "investigation.pivot.usernames": {"en": "Search the provided usernames in public sources and compare them with the retained email candidates.", "pt-br": "Pesquise os nomes de usuário fornecidos em fontes públicas e compare-os com os e-mails candidatos mantidos."},
    "investigation.pivot.organization": {"en": "Correlate the organization seed with public documents or breach references, treating all matches as OSINT leads rather than proof.", "pt-br": "Correlacione a organização inicial com documentos públicos ou referências de vazamentos, tratando todas as correspondências como pistas OSINT, não como prova."},
    "investigation.pivot.profiles": {"en": "Review the generated public-profile pivot URLs for platforms such as LinkedIn, Instagram, Facebook, GitHub, X, Spotify, Telegram, and Gravatar.", "pt-br": "Revise as URLs de pesquisa de perfis públicos geradas para plataformas como LinkedIn, Instagram, Facebook, GitHub, X, Spotify, Telegram e Gravatar."},
    "investigation.pivot.independent": {"en": "Treat inferred candidates as review leads until at least two independent public signals correlate.", "pt-br": "Trate candidatos inferidos como pistas para revisão até que pelo menos dois sinais públicos independentes se correlacionem."},
    "investigation.finding.profiles_matched": {"en": "{count} public profile URL(s) returned a resolvable public match signal.", "pt-br": "{count} URL(s) de perfis públicos retornaram um sinal público de correspondência resolvível."},
    "investigation.finding.profiles_missing": {"en": "{count} public profile URL(s) returned not found during collection.", "pt-br": "{count} URL(s) de perfis públicos retornaram resultado não encontrado durante a coleta."},
    "investigation.risk.profiles_blocked": {"en": "{count} platform check(s) were blocked, so account existence remains ambiguous.", "pt-br": "{count} verificação(ões) de plataforma foram bloqueadas, portanto a existência da conta permanece ambígua."},
    "investigation.risk.profiles_ambiguous": {"en": "{count} public profile check(s) were ambiguous and require manual verification.", "pt-br": "{count} verificação(ões) de perfis públicos foram ambíguas e exigem verificação manual."},
    "investigation.reason.generated_url": {"en": "Generated as a public URL pattern for manual review.", "pt-br": "Gerado como padrão de URL pública para revisão manual."},
    "investigation.limitation.generated_url": {"en": "A generated public-profile URL does not prove the profile exists or belongs to the email subject.", "pt-br": "Uma URL gerada de perfil público não comprova que o perfil exista ou pertença à pessoa associada ao e-mail."},
    "investigation.note.public_url": {"en": "Public URL generated for safe manual review.", "pt-br": "URL pública gerada para revisão manual segura."},
    "investigation.note.correlation": {"en": "Treat matches as possible correlations, not proof of identity ownership.", "pt-br": "Trate correspondências como possíveis correlações, não como prova de titularidade da identidade."},
    "investigation.limitation.indicators": {"en": "Results are OSINT indicators collected from public or permitted sources and should not be treated as definitive proof.", "pt-br": "Os resultados são indicadores OSINT coletados de fontes públicas ou permitidas e não devem ser tratados como prova definitiva."},
    "investigation.limitation.credentials": {"en": "The workflow does not collect passwords, test credentials, attempt logins, or use illicit sources.", "pt-br": "O fluxo não coleta senhas, testa credenciais, tenta logins ou utiliza fontes ilícitas."},
    "investigation.limitation.sensitive": {"en": "Sensitive details are masked in human-readable outputs when practical, but investigators should still handle exported data carefully.", "pt-br": "Detalhes sensíveis são mascarados nas saídas legíveis quando possível, mas os investigadores ainda devem tratar os dados exportados com cuidado."},
    "investigation.limitation.absence": {"en": "Absence of breach data or DNS signals does not prove an email or identity is safe, inactive, or nonexistent.", "pt-br": "A ausência de dados de vazamento ou sinais DNS não comprova que um e-mail ou identidade seja seguro, esteja inativo ou não exista."},
    "investigation.reason.hibp_found": {"en": "Public breach data references this email address.", "pt-br": "Dados públicos de vazamentos fazem referência a este endereço de e-mail."},
    "investigation.reason.hibp_none": {"en": "No known public HIBP breach record was returned; this is not positive identity evidence.", "pt-br": "Nenhum registro conhecido de vazamento público do HIBP foi retornado; isso não é evidência positiva de identidade."},
    "investigation.reason.hibp_status": {"en": "HIBP status was {status}; treat the result as a limitation, not confirmation.", "pt-br": "O status HIBP foi {status}; trate o resultado como uma limitação, não como confirmação."},
    "profile.error.timeout": {"en": "Public profile check timed out.", "pt-br": "A verificação do perfil público atingiu o tempo limite."},
    "profile.error.request": {"en": "Public profile check failed: {error}", "pt-br": "A verificação do perfil público falhou: {error}"},
    "profile.limitation.timeout": {"en": "Timeout prevents determining whether the public profile exists.", "pt-br": "O tempo limite impede determinar se o perfil público existe."},
    "profile.limitation.request": {"en": "Request errors prevent determining whether the public profile exists.", "pt-br": "Erros de consulta impedem determinar se o perfil público existe."},
    "profile.note.lab": {"en": "Lab-only scenario applied: {scenario}.", "pt-br": "Cenário exclusivo de laboratório aplicado: {scenario}."},
    "profile.evidence.summary": {"en": "Public profile check for {platform}/{handle} returned status {status}.", "pt-br": "A verificação do perfil público de {platform}/{handle} retornou o status {status}."},
    "profile.evidence.title": {"en": "Public profile resolution", "pt-br": "Resolução de perfil público"},
    "profile.reason.resolves": {"en": "Public URL returned a resolvable page signal.", "pt-br": "A URL pública retornou um sinal de página resolvível."},
    "profile.reason.weak_http": {"en": "HTTP success alone is retained only as weak public evidence.", "pt-br": "O sucesso HTTP isolado é mantido apenas como evidência pública fraca."},
    "profile.reason.not_found": {"en": "Public URL returned not found and is rejected as a profile lead.", "pt-br": "A URL pública retornou resultado não encontrado e foi descartada como pista de perfil."},
    "profile.reason.blocked": {"en": "Platform blocked the public check, so existence remains ambiguous.", "pt-br": "A plataforma bloqueou a verificação pública, portanto a existência permanece ambígua."},
    "profile.reason.rate_limited": {"en": "Platform rate-limited the public check, so existence remains ambiguous.", "pt-br": "A plataforma limitou a frequência da verificação pública, portanto a existência permanece ambígua."},
    "profile.reason.request_error": {"en": "Public profile check returned a request error.", "pt-br": "A verificação do perfil público retornou um erro de consulta."},
    "profile.reason.ambiguous": {"en": "Public profile signal is ambiguous and requires manual review.", "pt-br": "O sinal do perfil público é ambíguo e exige revisão manual."},
    "profile.reason.manual_review": {"en": "Public profile signal requires manual review.", "pt-br": "O sinal do perfil público exige revisão manual."},
    "profile.limitation.no_login": {"en": "Public profile checks do not use login, recovery, credential, or hidden endpoints.", "pt-br": "Verificações de perfis públicos não usam endpoints de login, recuperação, credenciais ou endpoints ocultos."},
    "profile.limitation.ownership": {"en": "A reachable profile URL does not prove ownership by the email subject.", "pt-br": "Uma URL de perfil acessível não comprova que pertença à pessoa associada ao e-mail."},
    "profile.limitation.correlation": {"en": "Independent public correlation is required before treating this as probable.", "pt-br": "É necessária uma correlação pública independente antes de tratar isso como provável."},
}
