"""English and Brazilian Portuguese copy for human-facing reports."""

CATALOG = {
    f"reporting.{key}": {"en": english, "pt-br": portuguese}
    for key, (english, portuguese) in {
        "analysis_title": ("MailRecon Analysis", "Análise MailRecon"),
        "report_title": ("MailRecon Report", "Relatório MailRecon"),
        "investigation_title": ("MailRecon Investigation", "Investigação MailRecon"),
        "investigation_report_title": ("MailRecon Investigation Report", "Relatório de Investigação MailRecon"),
        "smtp_title": ("MailRecon Lab SMTP Validation", "Validação SMTP em Laboratório MailRecon"),
        "lab_only": ("LAB ONLY - not evidence of real mailbox existence", "SOMENTE LABORATÓRIO - não comprova a existência de uma caixa de e-mail real"),
        "email": ("Email", "E-mail"),
        "domain": ("Domain", "Domínio"),
        "format_valid": ("Format valid", "Formato válido"),
        "domain_resolves": ("Domain resolves", "Domínio resolve"),
        "domain_status": ("Domain status", "Estado do domínio"),
        "mail_capability": ("Mail capability", "Capacidade de receber e-mail"),
        "provider_family": ("Provider family", "Família do provedor"),
        "technical_priority": ("Technical priority", "Prioridade técnica"),
        "technical_review_priority": ("Technical review priority", "Prioridade de revisão técnica"),
        "a_records": ("A records", "Registros A"),
        "mx_found": ("MX records found", "Registros MX encontrados"),
        "mx_hosts": ("MX hosts", "Servidores MX"),
        "mx_records": ("MX records", "Registros MX"),
        "spf_status": ("SPF status", "Estado do SPF"),
        "dmarc_status": ("DMARC status", "Estado do DMARC"),
        "role_account_status": ("Role account status", "Estado da conta funcional"),
        "disposable_status": ("Disposable status", "Estado de e-mail descartável"),
        "catch_all_status": ("Catch-all status", "Estado de aceitação universal"),
        "hibp_status": ("HIBP status", "Estado do HIBP"),
        "hibp_queried": ("HIBP queried", "HIBP consultado"),
        "hibp_breaches_found": ("HIBP breaches found", "Vazamentos encontrados no HIBP"),
        "hibp_breaches": ("HIBP breaches", "Vazamentos do HIBP"),
        "dns_notes": ("DNS notes", "Notas de DNS"),
        "hibp_notes": ("HIBP notes", "Notas do HIBP"),
        "technical_reasons": ("Technical assessment reasons", "Razões da avaliação técnica"),
        "technical_limitations": ("Technical assessment limitations", "Limitações da avaliação técnica"),
        "unknown_breach": ("Unknown breach", "Vazamento desconhecido"),
        "no_title": ("No title", "Sem título"),
        "generated_at": ("Generated at", "Gerado em"),
        "review_priority": ("Review priority", "Prioridade de revisão"),
        "overview": ("Overview", "Visão geral"),
        "platform": ("Platform", "Plataforma"),
        "name": ("Name", "Nome"),
        "html_empty": ("No records", "Sem registros"),
        "html_details": ("Decision details and manual links", "Detalhes de decisão e links manuais"),
        "html_collection": ("Collection performed", "Coleta realizada"),
        "html_timestamp": ("Recorded / observed at", "Registro / observação em"),
        "html_synthetic_notice": ("SYNTHETIC DEMO: every record is fictitious; no network query was made. Identity is not confirmed.", "DEMONSTRAÇÃO SINTÉTICA: todos os registros são fictícios; nenhuma consulta de rede foi feita. Identidade não confirmada."),
        "html_field": ("Field", "Campo"),
        "html_value": ("Value", "Valor"),
        "html_kind": ("Evidence state", "Estado da evidência"),
        "html_all": ("All states", "Todos os estados"),
        "html_hypothesis": ("Hypothesis / input", "Hipótese / entrada"),
        "html_observed": ("Observed signal", "Sinal observado"),
        "html_synthetic": ("Synthetic / lab", "Sintético / laboratório"),
        "html_rule": ("Rule / version", "Regra / versão"),
        "html_cache": ("Cached observation", "Observação em cache"),
        "html_dns": ("DNS observations", "Observações DNS"),
        "html_identity": ("Identity is not confirmed. Hypotheses, public observations and synthetic results are distinct; scores are triage heuristics, not probabilities.", "Identidade não confirmada. Hipóteses, observações públicas e resultados sintéticos são distintos; pontuações são heurísticas de triagem, não probabilidades."),
        "html_masked": ("Emails masked", "E-mails mascarados"),
        "html_revealed": ("Full emails visible", "E-mails completos visíveis"),
        "html_filter": ("Filter records", "Filtrar registros"),
        "html_reset": ("Clear filters", "Limpar filtros"),
        "seed_emails": ("Seed emails", "E-mails de origem"),
        "seed_usernames": ("Seed usernames", "Nomes de usuário de origem"),
        "seed_domains": ("Seed domains", "Domínios de origem"),
        "candidate_emails": ("Candidate emails", "E-mails candidatos"),
        "profile_pivots": ("Profile pivots", "Pivôs de perfis"),
        "public_profile_pivots": ("Public-profile pivots", "Pivôs de perfis públicos"),
        "retained_leads": ("Retained leads", "Pistas mantidas"),
        "exposure_signals": ("Exposure signals", "Sinais de exposição"),
        "evidence_records": ("Evidence records", "Registros de evidência"),
        "confidence_breakdown": ("Confidence breakdown", "Detalhamento da confiança"),
        "candidate_preview": ("Candidate preview", "Prévia dos candidatos"),
        "top_finding": ("Top finding", "Principal achado"),
        "primary_risk": ("Primary risk", "Principal risco"),
        "platform_preview": ("Platform preview", "Prévia das plataformas"),
        "review_links": ("Profile links to review", "Links de perfis para revisão"),
        "refinement": ("Refinement", "Refinamento"),
        "excluded_links": ("Excluded links", "Links excluídos"),
        "state_file": ("State file", "Arquivo de estado"),
        "refinement_file_path": ("Refinement file", "Arquivo de refinamento"),
        "refinement_excluded_links": ("Refinement excluded links", "Links excluídos no refinamento"),
        "names": ("Names", "Nomes"),
        "organizations": ("Organizations", "Organizações"),
        "context": ("Context", "Contexto"),
        "findings": ("Findings", "Achados"),
        "evidence": ("Evidence", "Evidências"),
        "risks": ("Risks", "Riscos"),
        "pivot_suggestions": ("Pivot suggestions", "Sugestões de pivô"),
        "limitations": ("Limitations", "Limitações"),
        "status": ("status", "estado"),
        "resolution_status": ("Resolution status", "Estado da resolução"),
        "source": ("Source", "Fonte"),
        "sources": ("Sources", "Fontes"),
        "confidence": ("Confidence", "Confiança"),
        "confidence_scope": ("Confidence scope", "Escopo da confiança"),
        "evidence_strength": ("Evidence strength", "Força da evidência"),
        "risk_level": ("Risk level", "Nível de risco"),
        "score": ("Score", "Pontuação"),
        "decision_reason": ("Decision reason", "Razão da decisão"),
        "ambiguity_reason": ("Ambiguity reason", "Razão da ambiguidade"),
        "matched_field": ("Matched field", "Campo correspondente"),
        "missing_field": ("Missing field", "Campo ausente"),
        "conflicting_field": ("Conflicting field", "Campo conflitante"),
        "limitation": ("Limitation", "Limitação"),
        "note": ("Note", "Nota"),
        "profile_url": ("Profile URL", "URL do perfil"),
        "search_url": ("Search URL", "URL de busca"),
        "final_url": ("Final URL", "URL final"),
        "http_status": ("HTTP status", "Estado HTTP"),
        "method": ("Method", "Método"),
        "summary": ("Summary", "Resumo"),
        "reference": ("Reference", "Referência"),
        "collected_at": ("Collected at", "Coletado em"),
        "observations": ("Observations", "Observações"),
        "handle": ("Handle", "Nome de usuário"),
        "mode": ("Mode", "Modo"),
        "lab_domain": ("Lab domain", "Domínio do laboratório"),
        "transport": ("Transport", "Transporte"),
        "host": ("Host", "Servidor"),
        "network_used": ("Network used", "Rede utilizada"),
        "safety_status": ("Safety status", "Estado de segurança"),
        "resolved_ips": ("Resolved IPs", "IPs resolvidos"),
        "safety_decision": ("Safety decision", "Decisão de segurança"),
        "checks": ("Checks", "Verificações"),
        "smtp_code": ("SMTP code", "Código SMTP"),
        "message": ("Message", "Mensagem"),
        "yes": ("yes", "sim"),
        "no": ("no", "não"),
        "state.none": ("none", "nenhuma"),
        "state.low": ("low", "baixa"),
        "state.medium": ("medium", "média"),
        "state.high": ("high", "alta"),
        "state.unknown": ("unknown", "desconhecido"),
        "state.unspecified": ("unspecified", "não especificado"),
        "state.generated_hypothesis": ("generated hypothesis", "hipótese gerada"),
        "state.input_seed": ("input seed", "dado inicial fornecido"),
        "state.provided_address": ("provided address", "endereço fornecido"),
        "state.direct_input_seed": ("direct input seed", "dado inicial fornecido diretamente"),
        "state.third_party_status": ("third-party status", "estado informado por terceiro"),
        "state.dns_observation": ("DNS observation", "observação de DNS"),
        "state.breach_exposure": ("breach exposure", "exposição em vazamentos"),
        "state.http_reachability": ("HTTP reachability", "acessibilidade HTTP"),
        "state.public_profile_existence": ("public profile existence", "existência de perfil público"),
        "state.synthetic_http_reachability": ("synthetic HTTP reachability", "acessibilidade HTTP simulada"),
        "state.lab_simulation": ("lab simulation", "simulação de laboratório"),
        "state.public_dns": ("public DNS", "DNS público"),
        "state.email_format": ("email format", "formato do e-mail"),
        "state.domain_configuration": ("domain configuration", "configuração do domínio"),
        "state.profile_existence": ("profile existence", "existência do perfil"),
        "state.identity_correlation": ("identity correlation", "correlação de identidade"),
        "state.email_format_confidence": ("Email format confidence", "Confiança no formato do e-mail"),
        "state.domain_confidence": ("DNS observation confidence", "Confiança na observação DNS"),
        "state.profile_existence_confidence": ("HTTP reachability confidence", "Confiança no alcance HTTP"),
        "state.identity_correlation_confidence": ("Identity correlation confidence", "Confiança na correlação de identidade"),
        "state.resolves": ("resolves", "resolve"),
        "state.nxdomain": ("nonexistent domain", "domínio inexistente"),
        "state.inconclusive": ("inconclusive", "inconclusivo"),
        "state.no_public_resolution": ("no public resolution", "sem resolução pública"),
        "state.declares_no_mail": ("declares no mail", "declara não aceitar e-mail"),
        "state.domain_unresolved": ("domain unresolved", "domínio não resolvido"),
        "state.mx_present": ("MX present", "MX presente"),
        "state.implicit_mail_possible": ("implicit mail possible", "recebimento implícito possível"),
        "state.no_mail_signal": ("no mail signal", "sem sinal de recebimento de e-mail"),
        "state.present": ("present", "presente"),
        "state.absent": ("absent", "ausente"),
        "state.multiple": ("multiple", "múltiplos"),
        "state.unknown_provider": ("unknown provider", "provedor desconhecido"),
        "state.google_workspace": ("Google Workspace", "Google Workspace"),
        "state.microsoft_365": ("Microsoft 365", "Microsoft 365"),
        "state.proton": ("Proton", "Proton"),
        "state.zoho": ("Zoho", "Zoho"),
        "state.fastmail": ("Fastmail", "Fastmail"),
        "state.icloud": ("iCloud", "iCloud"),
        "state.yahoo": ("Yahoo", "Yahoo"),
        "state.mailgun": ("Mailgun", "Mailgun"),
        "state.sendgrid": ("SendGrid", "SendGrid"),
        "state.amazon_ses": ("Amazon SES", "Amazon SES"),
        "state.cloudflare_email_routing": ("Cloudflare Email Routing", "Cloudflare Email Routing"),
        "state.improvmx": ("ImprovMX", "ImprovMX"),
        "state.role_account": ("role account", "conta funcional"),
        "state.not_role_account": ("not a role account", "não é conta funcional"),
        "state.disposable": ("disposable", "descartável"),
        "state.not_disposable": ("not disposable", "não descartável"),
        "state.not_tested": ("not tested", "não testado"),
        "state.not_checked": ("not checked", "não verificado"),
        "state.disabled": ("disabled", "desativado"),
        "state.missing_api_key": ("missing API key", "chave de API ausente"),
        "state.breaches_found": ("breaches found", "vazamentos encontrados"),
        "state.no_breaches": ("no breaches", "nenhum vazamento"),
        "state.timeout": ("timeout", "tempo limite excedido"),
        "state.request_error": ("request error", "erro na requisição"),
        "state.unauthorized": ("unauthorized", "não autorizado"),
        "state.forbidden": ("forbidden", "proibido"),
        "state.rate_limited": ("rate limited", "limite de requisições atingido"),
        "state.http_error": ("HTTP error", "erro HTTP"),
        "state.invalid_response": ("invalid response", "resposta inválida"),
        "state.valid": ("valid", "válido"),
        "state.accepted_direct_seed": ("accepted direct seed", "dado inicial direto aceito"),
        "state.candidate_generated": ("candidate generated", "candidato gerado"),
        "state.format_valid_unverified": ("valid format, unverified", "formato válido, não verificado"),
        "state.invalid": ("invalid", "inválido"),
        "state.manual_review": ("manual review", "revisão manual"),
        "state.retained_for_manual_review": ("retained for manual review", "mantido para revisão manual"),
        "state.rejected_invalid_format": ("rejected: invalid format", "rejeitado: formato inválido"),
        "state.rejected_domain_unresolved": ("rejected: domain unresolved", "rejeitado: domínio não resolvido"),
        "state.rejected_domain_no_mail": ("rejected: domain accepts no mail", "rejeitado: domínio não aceita e-mail"),
        "state.rejected_profile_not_found": ("rejected: profile not found", "rejeitado: perfil não encontrado"),
        "state.blocked_cannot_determine": ("blocked: cannot determine", "bloqueado: não é possível determinar"),
        "state.ambiguous_requires_review": ("ambiguous: requires review", "ambíguo: requer revisão"),
        "state.public_match_possible": ("public match possible", "correspondência pública possível"),
        "state.not_found": ("not found", "não encontrado"),
        "state.blocked_by_platform": ("blocked by platform", "bloqueado pela plataforma"),
        "state.ambiguous": ("ambiguous", "ambíguo"),
        "state.weak_inferred": ("weak inferred evidence", "evidência inferida fraca"),
        "state.weak_public_http": ("weak public HTTP evidence", "evidência HTTP pública fraca"),
        "state.moderate_public_api": ("moderate public API evidence", "evidência moderada de API pública"),
        "state.synthetic": ("synthetic evidence", "evidência sintética"),
        "state.official_public_api": ("official public API", "API pública oficial"),
        "state.manual_only": ("manual only", "apenas manual"),
        "state.public_profile_id": ("public profile ID", "ID de perfil público"),
        "state.exact_handle": ("exact handle", "usuário exato"),
        "state.canonical_profile_url": ("canonical profile URL", "URL canônica de perfil"),
        "state.invalid_pivot": ("invalid pivot", "pivô inválido"),
        "state.source_disabled": ("source disabled", "fonte desabilitada"),
        "state.budget_exhausted": ("request budget exhausted", "orçamento de consultas esgotado"),
        "state.invalid_payload": ("invalid API payload", "resposta de API inválida"),
        "state.response_too_large": ("response too large", "resposta excede limite"),
        "state.unexpected_response_url": ("unexpected response URL", "URL de resposta inesperada"),
        "state.unexpected_http_status": ("unexpected HTTP status", "status HTTP inesperado"),
        "state.moderate_format_and_dns": ("moderate format and DNS evidence", "evidência moderada de formato e DNS"),
        "state.strong_direct_seed": ("strong direct seed evidence", "evidência forte de dado inicial direto"),
        "state.moderate_third_party_status": ("moderate third-party status evidence", "evidência moderada de estado informado por terceiro"),
        "state.seed_email": ("seed email", "e-mail de origem"),
        "state.seed_candidate": ("seed candidate", "candidato de origem"),
        "state.provided_candidate": ("provided candidate", "candidato fornecido"),
        "state.username_domain_inference": ("username/domain inference", "inferência por usuário/domínio"),
        "state.name_domain_inference": ("name/domain inference", "inferência por nome/domínio"),
        "state.public_profile_pivot": ("public-profile pivot", "pivô de perfil público"),
        "state.investigator_input": ("investigator input", "entrada do investigador"),
        "state.manual_input": ("manual input", "entrada manual"),
        "state.public_profile_check": ("public profile check", "verificação de perfil público"),
        "state.lab_public_profile_check": ("lab public profile check", "verificação de perfil público em laboratório"),
        "state.login_search_or_challenge_redirect": ("login, search or challenge redirect", "redirecionamento para login, busca ou desafio"),
        "state.http_success_without_profile_specific_evidence": ("HTTP success without profile-specific evidence", "sucesso HTTP sem evidência específica do perfil"),
        "state.profile_url_resolved": ("profile URL resolved", "URL do perfil resolvida"),
        "state.independent_identity_correlation": ("independent identity correlation", "correlação independente de identidade"),
        "state.public_profile": ("public profile", "perfil público"),
        "state.deterministic_profile_state": ("deterministic profile state", "estado determinístico do perfil"),
        "state.blocked_by_safety_policy": ("blocked by safety policy", "bloqueado pela política de segurança"),
        "state.allowed_lab_only": ("allowed in lab only", "permitido somente em laboratório"),
        "state.mock": ("mock", "simulado"),
        "state.mocked_accept": ("mocked acceptance", "aceitação simulada"),
        "state.mocked_reject": ("mocked rejection", "rejeição simulada"),
        "state.connection_failed": ("connection failed", "falha na conexão"),
        "state.check_not_supported": ("check not supported", "verificação não suportada"),
        "state.accepted": ("accepted", "aceito"),
        "state.rejected": ("rejected", "rejeitado"),
        "state.temporary_failure": ("temporary failure", "falha temporária"),
        "state.accepted_by_lab_server": ("accepted by lab server", "aceito pelo servidor de laboratório"),
        "state.rejected_by_lab_server": ("rejected by lab server", "rejeitado pelo servidor de laboratório"),
        "state.temporarily_unavailable": ("temporarily unavailable", "temporariamente indisponível"),
    }.items()
}
